In [ ]:
import numpy as np

In [ ]:
a=np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], [[90, 100, 111, 121], [15, 16, 17, 18], [12, 22, 23, 42]]])
print(a[0:2, 1:3, :])

In [ ]:
for x in np.nditer(a):
    print(x, end=" ")

In [ ]:
arr=np.arange(1, 11)
print(arr*3)

In [ ]:
arr=np.arange(1, 13)
new=arr.reshape(3, 4)
print(new[2, 3])

In [ ]:
arr = np.array([100, 200, 300, 400, 500])
view_arr = arr[-3:].view()

view_arr[0] = 999
print("Shared array: ", view_arr)
print("Original array: ", arr)


In [ ]:
arr = np.array([100, 200, 300, 400, 500])
copied = arr.copy()
copied[0] = 999
print("Copied: ", copied)
print("Original array: ", arr)

In [ ]:
def sum_even_only(arr):
    total=0
    for x in np.nditer(arr):
        if x%2==0:
            total+=x
    return total
a=np.array([[1, 2, 3], [4, 5, 6]])
print(sum_even_only(a))

In [ ]:
arr=np.array([5, 12, 8, 20, 3, 17, 9, 25])
new=np.array_split(arr, 4)
for i in new:
    print(i, end=" ")


In [ ]:
mask=np.where(arr>10)
print(mask)


In [ ]:
def top_n_scores(scores, n):
    sorted_data=np.sort(scores)
    return sorted_data[-n:]
print(top_n_scores(np.array([45, 82, 10, 96, 33, 77]), 2))

In [2]:
import numpy as np
data = np.random.normal(loc=50, scale=10, size=1000)
print(data)

[45.07873213 52.68042311 49.03882756 57.59245907 39.58190078 65.53896993
 46.14446345 45.06083179 36.40387116 38.08100107 59.63326204 44.62596965
 51.05293798 49.80971371 47.9954324  52.90400582 43.82378131 52.82923301
 61.97285387 39.14395886 42.61402506 39.91516307 33.55020596 40.59457514
 26.82157654 37.7045834  60.54326883 51.87640859 48.15722864 57.91258817
 41.96779183 43.76449039 42.32233429 59.76391392 39.82298288 51.84386469
 33.70407487 63.50584091 38.05201667 53.48279788 41.71457667 61.34565601
 62.05629899 61.11677451 64.33348007 47.22856273 51.67235256 61.15811079
 45.6203201  60.36909521 56.41374197 34.08325086 41.16202915 28.12443601
 44.74796841 38.9637671  64.16531843 44.09321425 28.39577919 49.81527563
 49.62588007 35.48504612 35.1086126  46.56597703 58.26317938 33.73334431
 51.66385482 47.17711628 51.40380674 37.74427801 59.34479995 38.14839554
 49.6828153  41.36052415 66.60631258 52.15832737 30.19288373 51.81146467
 45.35335633 65.92912878 74.52493394 52.34454808 46

In [19]:
a = np.array([10, 20, 30])
b = np.array([3, 4, 7])
print(np.mod(a, b))

[1 0 2]


In [3]:
arr=np.zeros((4,4))
for i in range(len(arr)):
    arr[i][i]=1
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [4]:
#Euclidean distance
def euc_dist(a, b):
    total=0
    for i in range(len(a)):
        total+=(a[i]-b[i])**2
    return total**0.5
a= [0, 0]
b= [3, 4]
print(euc_dist(a, b))


5.0


In [5]:
import numpy as np
a= np.array([0, 0])
b= np.array([3, 4])
print(np.linalg.norm(a-b))

5.0
