In [ ]:
import numpy as np

In [9]:
a=np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], [[90, 100, 111, 121], [15, 16, 17, 18], [12, 22, 23, 42]]])
print(a[0:2, 1:3, :])

[[[ 5  6  7  8]
  [ 9 10 11 12]]

 [[15 16 17 18]
  [12 22 23 42]]]


In [11]:
for x in np.nditer(a):
    print(x, end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 90 100 111 121 15 16 17 18 12 22 23 42 

In [12]:
arr=np.arange(1, 11)
print(arr*3)

[ 3  6  9 12 15 18 21 24 27 30]


In [15]:
arr=np.arange(1, 13)
new=arr.reshape(3, 4)
print(new[2, 3])

12


In [27]:
arr = np.array([100, 200, 300, 400, 500])
view_arr = arr[-3:].view()

view_arr[0] = 999
print("Shared array: ", view_arr)
print("Original array: ", arr)


Shared array:  [999 400 500]
Original array:  [100 200 999 400 500]


In [28]:
arr = np.array([100, 200, 300, 400, 500])
copied = arr.copy()
copied[0] = 999
print("Copied: ", copied)
print("Original array: ", arr)

Copied:  [999 200 300 400 500]
Original array:  [100 200 300 400 500]


In [34]:
def sum_even_only(arr):
    total=0
    for x in np.nditer(arr):
        if x%2==0:
            total+=x
    return total
a=np.array([[1, 2, 3], [4, 5, 6]])
print(sum_even_only(a))

12


In [40]:
arr=np.array([5, 12, 8, 20, 3, 17, 9, 25])
new=np.array_split(arr, 4)
for i in new:
    print(i, end=" ")


[ 5 12] [ 8 20] [ 3 17] [ 9 25] 

In [ ]:
mask=np.where(arr>10)
print(mask)


(array([1, 3, 5, 7]),)


In [ ]:
def top_n_scores(scores, n):
    sorted_data=np.sort(scores)
    return np.sort(sorted_data[-3:])
print(top_n_scores(np.array([45, 82, 10, 96, 33, 77]), 3))