In [1]:
import numpy as np

In [3]:
np.random.seed(42)
random_values=np.random.normal(loc=100, scale=15, size=1000)
print(random_values[:5])


[107.4507123   97.92603548 109.71532807 122.84544785  96.48769938]


In [9]:
def simulate_emotions(n):
    np.random.seed(1)
    return np.random.choice(["joy", "sadness", "anger"], n,  p=[0.6, 0.25, 0.15])
     
print(simulate_emotions(10))


['joy' 'sadness' 'joy' 'joy' 'joy' 'joy' 'joy' 'joy' 'joy' 'joy']


In [10]:
data = np.array([1, 2, 3, 4, 5])
print(np.random.permutation(data))
print(data)

[2 5 4 1 3]
[1 2 3 4 5]


In [12]:
def simulate_responses(num_users, num_prompts, response_rate):
    return np.random.binomial(num_prompts, response_rate, num_users)
print(simulate_responses(5,20,0.7))

[16 15 16 12 15]


In [14]:
np.random.seed(7)
arr=np.random.normal(loc=50, scale=10, size=1000)
new=len(arr[arr>60])
percent=(new/1000)*100

print(percent)

14.899999999999999
